version: '3.8'

services:
  web:
    image: ghcr.io/amarajanic/fast-api-template:latest  # Use the built image
    restart: always
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --reload
